# Dockerfile for the worker
FROM python:3.11-slim-bookworm

RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify AV1 support because not all version of ffmpeg support it.
RUN ffmpeg -encoders | grep libsvtav1

WORKDIR /app
RUN pip install requests
ENTRYPOINT ["/bin/sh", "-c", "curl -s -o worker.py https://encode.fractumseraph.net/dl/worker && python worker.py \"$@\"", "--"]
