# This container is for the worker, not server!
FROM python:3.11-slim-bookworm

RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# This Program requires libsvtav1, not all ffmpeg versions have it.
RUN ffmpeg -encoders | grep libsvtav1

WORKDIR /app
RUN pip install requests
COPY worker.py .
ENTRYPOINT ["python", "worker.py"]
